[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  framework = "vite"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
